# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import celery
import pretend
import pytest

from sqlalchemy.orm.exc import NoResultFound

import warehouse.malware.checks as checks

from warehouse.malware.models import MalwareVerdict
from warehouse.malware.tasks import run_check

from ...common.db.malware import MalwareCheckFactory
from ...common.db.packaging import FileFactory, ProjectFactory, ReleaseFactory


def test_run_check(monkeypatch, db_request):
    project = ProjectFactory.create(name="foo")
    release = ReleaseFactory.create(project=project)
    file0 = FileFactory.create(release=release, filename="foo.bar")
    MalwareCheckFactory.create(name="ExampleCheck", state="enabled")

    task = pretend.stub()
    run_check(task, db_request, "ExampleCheck", file0.id)
    assert db_request.db.query(MalwareVerdict).one()


def test_run_check_missing_check_id(monkeypatch, db_session):
    exc = NoResultFound("No row was found for one()")

    class FakeMalwareCheck:
        def __init__(self, db):
            raise exc

    class Task:
        @staticmethod
        @pretend.call_recorder
        def retry(exc):
            raise celery.exceptions.Retry

    task = Task()

    checks.FakeMalwareCheck = FakeMalwareCheck

    request = pretend.stub(
        db=db_session,
        log=pretend.stub(error=pretend.call_recorder(lambda *args, **kwargs: None),),
    )

    with pytest.raises(celery.exceptions.Retry):
        run_check(
            task, request, "FakeMalwareCheck", "d03d75d1-2511-4a8b-9759-62294a6fe3a7"
        )

    assert request.log.error.calls == [
        pretend.call(
            "Error executing check %s: %s",
            "FakeMalwareCheck",
            "No row was found for one()",
        )
    ]

    assert task.retry.calls == [pretend.call(exc=exc)]


def test_run_check_missing_check(db_request):
    task = pretend.stub()
    with pytest.raises(AttributeError):
        run_check(
            task,
            db_request,
            "DoesNotExistCheck",
            "d03d75d1-2511-4a8b-9759-62294a6fe3a7",
        )
